services:
  - type: web
    name: code-formatter
    env: docker
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FORMATTER_TIMEOUT
        value: "10"
      - key: FORMATTER_WORKERS
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx64m -Xms16m"